version: '3.8'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foodie
    ports:
      - "3306:3306"

  restaurants:
    build: ./backend/restaurants
    depends_on:
      - mysql
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend/my-foodie-app
    depends_on:
      - restaurants
    ports:
      - "80:80"
