version: '3.7'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foodie
    ports:
      - "3306:3306"

  restaurant-service:   
    build: ./backend/restaurant-service
    depends_on:
      - mysql
    ports:
      - "8081:8081"

  frontend:    
    build: ./frontend/my-foodie-app
    depends_on:
      - restaurant-service
    ports:
      - "80:80"
